; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "QTVODm2"
!define PRODUCT_VERSION "1.3RC3-devel"
!define PRODUCT_PUBLISHER "IFSTTAR"
!define PRODUCT_WEB_SITE "http://www.inrets.fr"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\QTVODm2.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

SetCompressor lzma
ShowInstDetails show

; MUI 1.67 compatible ------
!include "MUI.nsh"
!include "FontRegAdv.nsh"
!include "FontName.nsh"
!include "winmessages.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

;--------------------------------
;Interface Configuration

!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "S:\MacOSX\QTilities\QTVODm2inst.bmp"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; setting env.vars:
!define env_hklm 'HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"'

;Request application privileges for Windows Vista
RequestExecutionLevel admin

var QTDIR

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
;  SetBrandingImage /RESIZETOFIT "S:\MacOSX\QTilities\QTils\QTils.ico"
  SetAutoClose false
  SetRegView 32
  ReadRegStr $0 HKLM "SOFTWARE\Apple Computer, Inc.\QuickTime" "InstallDir"
  IfErrors 0 +3
           MessageBox MB_ICONEXCLAMATION|MB_OK "QuickTime is required. http://www.apple.com/quicktime/download"
           Abort "QuickTime is required. http://www.apple.com/quicktime/download "
  StrCpy $QTDIR $0
  DetailPrint "QuickTime is installed in $QTDIR"
;  MessageBox MB_ICONEXCLAMATION|MB_OK "QuickTime is installed in $QTDIR"
FunctionEnd

; Welcome page
!insertmacro MUI_PAGE_WELCOME
Page Custom LockedListShow
; Components page
Function LockedListShow
  !insertmacro MUI_HEADER_TEXT "$(KillProcs1)" "$(KillProcs2)"
  LockedList::AddModule "QTVODm2.exe"
  LockedList::AddModule "\QTImage2Mov.qtx"
  LockedList::AddModule "\QTImage2Mov-dev.qtx"
  LockedList::AddModule "\QTils.dll"
  LockedList::AddModule "\QTils-dev.dll"
  LockedList::AddModule "\POSIXm2.dll"
  LockedList::AddModule "\POSIXm2-dev.dll"
  LockedList::AddModule "\SS_Log_Window.exe"
  LockedList::AddModule "\SS_Log_AddIn.dll"
  LockedList::Dialog /autonext /autoclose "" "" "" ""
    pop $R0
FunctionEnd

Section
SectionEnd

!insertmacro MUI_PAGE_COMPONENTS
; Directory page
!insertmacro MUI_PAGE_DIRECTORY

; Start menu page
;var ICONS_GROUP
;!define MUI_STARTMENUPAGE_NODISABLE
;!define MUI_STARTMENUPAGE_DEFAULTFOLDER "QTVODm2"
;!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
;!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
;!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
;!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP

; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "French"
!insertmacro MUI_LANGUAGE "English"

; Reserve files
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "QTVODm2-v${PRODUCT_VERSION}-dev-installer.exe"
InstallDir "$EXEDIR\QTVODm2"
; Icon "S:\MacOSX\QTilities\QTils\QTils.ico"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

; AddBrandingImage left 128


LangString Name ${LANG_ENGLISH} "English"
LangString Name ${LANG_FRENCH} "French"
LangString Sec2Name ${LANG_ENGLISH} "QTVODm2 Player"
LangString Sec2Name ${LANG_FRENCH} "Lecteur QTVODm2"
LangString Sec1Descr ${LANG_ENGLISH} "The QuickTime Importer QTImage2Mov that allows to import VOD and Qi2M files. Installs in $QTDIR QTComponents"
LangString Sec2Descr ${LANG_ENGLISH} "The QTVODm2 Player application and an example launch script and config file"
LangString Sec3Descr ${LANG_ENGLISH} "Documentation for QTVODm2, QTImage2Mov and QTilities"
LangString Sec4Descr ${LANG_ENGLISH} "Modula-2 sources and projects"
LangString Sec5Descr ${LANG_ENGLISH} "SS_Log logging facility (into $WINDIR)"
LangString Sec6Descr ${LANG_ENGLISH} "libraries SS_Log logging facility (into c:\Libs\ SS_Log_Bin)"
LangString Sec1Descr ${LANG_FRENCH} "Le 'QuickTime Importer' QTImage2Mov qui permet d'importer les fichiers VOD et QI2M dans QuickTime.  s'Installe dans $QTDIR QTComponents"
LangString Sec2Descr ${LANG_FRENCH} "Le Lecteur QTVODm2 ainsi qu'un exemple de script de lancement et de fichier de configuration"
LangString Sec3Descr ${LANG_FRENCH} "Documentation pour QTVODm2, QTImage2Mov et QTilities"
LangString Sec4Descr ${LANG_FRENCH} "sources et projets Modula-2"
LangString Sec5Descr ${LANG_FRENCH} "SS_Log: fonctions journal (pour $WINDIR)"
LangString Sec6Descr ${LANG_FRENCH} "libraires pour les fonctions journal SS_Log (pour c:\Libs\SS_Log_Bin)"
LangString Sec7Descr ${LANG_ENGLISH} "Font used for the time and GPS info track in imported videos"
LangString Sec7Descr ${LANG_FRENCH} "La police utilisée pour la piste d'horodatage et GPS dans les vidéos importées"
LangString Sec8Descr ${LANG_ENGLISH} "FFmpeg and FFprobe (32 bit versions), used by the QTImage2Mov Importer. Installs in $QTDIR QTSystem"
LangString Sec8Descr ${LANG_FRENCH} "FFmpeg et FFprobe (versions 32 bit), utilisés par le plugin QTImage2Mov. s'Installent dans $QTDIR QTSystem"
LangString QI2Mfail  ${LANG_ENGLISH} "could not be installed; to be copied manually into"
LangString QI2Mfail  ${LANG_FRENCH} "echec d'installation, à copier à la main dans"
LangString DirSelectSText  ${LANG_ENGLISH} "Install dir (QTImage2Mov will go into $QTDIR QTComponents!)"
LangString DirSelectSText  ${LANG_FRENCH} "Répertoire d'installation (QTImage2Mov ira dans $QTDIR QTComponents!)"
LangString AuthorText  ${LANG_ENGLISH} "QTImage2Mov and QTVODm2 © 2010-2012 R.J.V. Bertin/INRETS/IFSTTAR; SS_Log © S. Schaneville. Icon by N.D. Oppong. NB: QTilsM2 will load the dev versions of QTils.dll and POSIXm2.dll if they exist."
LangString AuthorText  ${LANG_FRENCH} "QTImage2Mov et QTVODm2 © 2010-2012 R.J.V. Bertin/INRETS/IFSTTAR; SS_Log © S. Schaneville. Icone par N.D. Oppong. NB: QTilsM2 chargera les versions 'dev' de QTils.dll et POSIXm2.dll si elles existent."
LangString KillProcs1   ${LANG_ENGLISH} "Please wait"
LangString KillProcs1   ${LANG_FRENCH} "Merci de patienter"
LangString KillProcs2   ${LANG_ENGLISH} "Verifying running processes"
LangString KillProcs2   ${LANG_FRENCH} "Verification des processus en cours d'execution"

DirText "" "$(DirSelectSText)"

ComponentText "$(AuthorText)"


Section "QuickTime VOD & Qi2M Importer Component" SEC01
  SetRegView 32
;  ReadRegStr $0 HKLM "SOFTWARE\Apple Computer, Inc.\QuickTime" "InstallDir"
;  IfErrors 0 +2
;           Abort "QuickTime is required"
  DetailPrint "QuickTime is installed in $QTDIR"
  KillProcDLL::KillProc "QuickTimePlayer.exe"
  DetailPrint "KillProc QuickTimePlayer returned $R0"
  KillProcDLL::KillProc "QTVODm2.exe"
  DetailPrint "KillProc QTVODm2 returned $R0"
  KillProcDLL::KillProc "Safari.exe"
  DetailPrint "KillProc Safari returned $R0"
  SetOutPath "$QTDIR\QTComponents"
  SetOverwrite ifnewer
  Delete "$QTDir\QTComponents\QTImage2Mov.qtx"
  File "S:\MacOSX\QTImage2Mov\QTImage2Mov-dev.qtx"
  IfErrors 0 +2
           MessageBox MB_ICONEXCLAMATION|MB_OK "QTImage2Mov $(QI2Mfail) $QTDIR\QTComponents"
  SetOutPath "$QTDIR\QTComponents-disabled"
  SetOverwrite ifnewer
  File /nonfatal "S:\MacOSX\QTImage2Mov\QTImage2Mov.qtx"
;  Sleep 1000

SectionEnd

Section "FFmpeg" SEC08
  SetRegView 32
  KillProcDLL::KillProc "ffmpeg.exe"
  DetailPrint "KillProc ffmpeg returned $R0"
  KillProcDLL::KillProc "ffprobe.exe"
  DetailPrint "KillProc ffprobe returned $R0"
  SetOutPath "$QTDIR\QTSystem"
  SetOverwrite ifnewer
  File "d:\Cygwin\bin\ffmpeg.exe"
  File "d:\Cygwin\bin\ffprobe.exe"
SectionEnd

Section !$(Sec2Name) SEC02
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "S:\MacOSX\QTilities\QTils\Mod2\QTVODm2.exe"
  File "S:\MacOSX\QTilities\QTils\Mod2\LanceQTVODm2.bat"
  File "S:\MacOSX\QTilities\QTils\Mod2\VODdesign.xml"
  File "S:\MacOSX\QTilities\QTils\QTils.dll"
  File "S:\MacOSX\QTilities\QTils\POSIXm2.dll"
  File "S:\MacOSX\QTilities\QTils\QTils-dev.dll"
  File "S:\MacOSX\QTilities\QTils\POSIXm2-dev.dll"
  CreateShortCut "$INSTDIR\QTVODm2-mjpeg2M.lnk" "$INSTDIR\QTVODm2.exe" "-fcodec mjpeg -fbitrate 2000k"
  CreateShortCut "$INSTDIR\QTVODm2-mjpeg2M-fsplit.lnk" "$INSTDIR\QTVODm2.exe" "-fcodec mjpeg -fbitrate 2000k -fsplit TRUE"
  CreateShortCut "$INSTDIR\QTVODm2-mpeg2-fsplit.lnk" "$INSTDIR\QTVODm2.exe" "-fcodec mpeg2video -fbitrate 4000k -fsplit TRUE"
  WriteRegExpandStr ${env_hklm} "QTMW_DoubleBuffering" "true"
  ; make sure windows knows about the change
  SendMessage ${HWND_BROADCAST} ${WM_WININICHANGE} 0 "STR:Environment" /TIMEOUT=5000
; Shortcuts
;  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
;  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "Documentation" SEC03
  SetOutPath "$INSTDIR\Documentation"
  SetOverwrite ifnewer
  File /nonfatal "S:\MacOSX\QTilities\QTVODm2.pdf"
  File /nonfatal "S:\MacOSX\QTilities\QTilities-v1.3.pdf"
  File /nonfatal /r "S:\MacOSX\QTilities\FFmpeg-licenses"
  File /nonfatal "S:\MacOSX\QTilities\ffmpeg-20121125-git-26c531c-win64-static-readme.txt"
  File /nonfatal "S:\MacOSX\QTImage2Mov\QTImage2Mov-v1.2.pdf"
  File /nonfatal "S:\MacOSX\QTilities\QTils.chm"
  File /nonfatal "S:\MacOSX\QTImage2Mov\QTImage2Mov.chm"

SectionEnd

Section /o $(Sec4Descr) SEC04
  SetOutPath "$INSTDIR\Mod2\mod"
  SetOverwrite ifnewer
  File "S:\MacOSX\QTilities\QTils\Mod2\mod\QTilsM2.mod"
  File "S:\MacOSX\QTilities\QTils\Mod2\mod\POSIXm2.mod"
  File "S:\MacOSX\QTilities\QTils\Mod2\mod\Chaussette2.mod"
  File "S:\MacOSX\QTilities\QTils\Mod2\mod\TstQTilsM2.mod"
  File "S:\MacOSX\QTilities\QTils\Mod2\mod\QTVOD*.mod"
  File "S:\MacOSX\QTilities\QTils\Mod2\mod\TstQTVDSrv.mod"
  SetOutPath "$INSTDIR\Mod2\def"
  SetOverwrite ifnewer
  File "S:\MacOSX\QTilities\QTils\Mod2\def\QTilsM2.def"
  File "S:\MacOSX\QTilities\QTils\Mod2\def\POSIXm2.def"
  File "S:\MacOSX\QTilities\QTils\Mod2\def\Chaussette2.def"
  File "S:\MacOSX\QTilities\QTils\Mod2\def\QTVOD*.def"
  SetOutPath "$INSTDIR\Mod2"
  SetOverwrite ifnewer
  File "S:\MacOSX\QTilities\QTils\Mod2\QTVOD*.res"
  File "S:\MacOSX\QTilities\QTils\Mod2\QTVODm2_local.sbs"
  File "S:\MacOSX\QTilities\QTils\Mod2\TstQTilsM2.sbs"
SectionEnd

Section "SS_Log" SEC05
  SetOutPath $WINDIR
  SetOverwrite ifnewer
  File "C:\Libs\SS_Log_bin\SS_Log_Window.exe"
  File /nonfatal "C:\Libs\SS_Log_bin\SS_Log_AddIn.dll"
SectionEnd

Section /o "SS_Log lib" SEC06
  SetOutPath "C:\Libs"
  SetOverwrite ifnewer
  File /r "C:\Libs\SS_Log_bin"
SectionEnd

Section "Monaco.ttf" SEC07
  StrCpy $FONT_DIR $FONTS
  !insertmacro InstallTTF "S:\MacOSX\QTImage2Mov\Monaco.ttf"
  SendMessage ${HWND_BROADCAST} ${WM_FONTCHANGE} 0 0 /TIMEOUT=5000
SectionEnd

;Section -AdditionalIcons
;  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
;  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
;  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
;  !insertmacro MUI_STARTMENU_WRITE_END
;SectionEnd

;Section -Post
;  WriteUninstaller "$INSTDIR\uninst.exe"
;  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\QTVODm2.exe"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\QTVODm2.exe"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
;SectionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} $(Sec1Descr)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC08} $(Sec8Descr)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC02} $(Sec2Descr)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC03} $(Sec3Descr)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC04} $(Sec4Descr)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC05} $(Sec5Descr)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC06} $(Sec6Descr)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC07} $(Sec7Descr)
!insertmacro MUI_FUNCTION_DESCRIPTION_END


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

;Section Uninstall
;  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
;  Delete "$INSTDIR\uninst.exe"
;  Delete "$INSTDIR\QTImage2Mov-v1.1.pdf"
;  Delete "$INSTDIR\QTImage2Mov.qtx"
;  Delete "$INSTDIR\QTilities-v1.2.pdf"
;  Delete "$INSTDIR\POSIXm2.dll"
;  Delete "$INSTDIR\QTils.dll"
;  Delete "$INSTDIR\VODdesign.xml"
;  Delete "$INSTDIR\LanceQTVODm2.bat"
;  Delete "$INSTDIR\QTVODm2.exe"
;
;  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
;
;  RMDir "$SMPROGRAMS\$ICONS_GROUP"
;  RMDir "$INSTDIR"
;
;  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
;  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
;  SetAutoClose true
;SectionEnd
